### ISSUE TITLE
is property="twitter:description" and not name="twitter:description"

### ISSUE THREAD

**Issue by depfryer** [troxler/headful#3]
hi 
i dont know what to say more than title ^^'
as you can see here [https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started)

thank you

**Comment by troxler** [comment]
I don't see anything wrong here. Maybe you are confusing Twitter tags with Open Graph tags?

> Open Graph protocol also specifies the use of property and content attributes for markup [...] while Twitter cards use name and content.
